name: Run HCL Bank Mobile and API Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest with HTML report
        run: |
          pytest --cov-report=html --cov=your_module -m "marker_name" --html=report.html

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./htmlcov/coverage.xml
          fail_ci_if_error: true

      - name: Archive HTML report
        uses: actions/upload-artifact@v2
        with:
          name: html-report
          path: ./htmlcov
